const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.video,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio.Cnds.OnFadeEnded,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{B_Back: 0},
	{B_No: 0},
	{B_Yes: 0},
	{Solid: 0},
	{Collision: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{"8Direction": 0},
	{MChar: 0},
	{Video: 0},
	{NA_S1_S2: 0},
	{NA_S2_S1: 0},
	{NA_S2_S3: 0},
	{Audio: 0},
	{Mouse: 0},
	{Fade: 0},
	{Fade_in: 0},
	{Fade_out: 0},
	{NA_S3_S2: 0},
	{Teclado: 0},
	{MakingSound: 0},
	{PlayerStartLocationX: 0},
	{PlayerStartLocationY: 0}
];

self.InstanceType = {
	B_Back: class extends self.ISpriteInstance {},
	B_No: class extends self.ISpriteInstance {},
	B_Yes: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	MChar: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	NA_S1_S2: class extends self.ISpriteInstance {},
	NA_S2_S1: class extends self.ISpriteInstance {},
	NA_S2_S3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Fade_in: class extends self.ISpriteInstance {},
	Fade_out: class extends self.ISpriteInstance {},
	NA_S3_S2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {}
}